version: 0.2

phases:
  install:
    runtime-versions:
        nodejs: 10
    commands:
      #- npm install -g n
      - n stable
      #- npm install

  pre_build:
    commands:
      - npm install --quiet --global expo-cli

  build:
    commands:
      - echo Build started on `date`
      - expo build:web
      
  post_build:
    commands:
      - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION --paths "/*"
  
artifacts:
  files:
    - '**/*'
  base-directory: web-build